version: '3.8'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

x-runner-common:
  &runner-common
  restart: always
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    build: ./server
    container_name: vigilant-server
    ports:
      - "3333:3333"
    volumes:
      - ./vigilant.conf:/etc/vigilant/vigilant.conf:ro
    env_file: vigilant.conf
    depends_on:
      db:
        condition: service_healthy
      runner-c:
        condition: service_started
      runner-cpp:
        condition: service_started
      runner-js:
        condition: service_started
      runner-java:
        condition: service_started
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    container_name: vigilant-db
    env_file: vigilant.conf
    volumes:
      - postgres_data:/var/lib/postgresql/data
    <<: *default-logging
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vigilant"]
      interval: 10s
      timeout: 5s
      retries: 5

  runner-c:
    build:
      context: ./server/runners
      dockerfile: c/Dockerfile
    container_name: vigilant-runner-c
    <<: *runner-common

  runner-cpp:
    build:
      context: ./server/runners
      dockerfile: cpp/Dockerfile
    container_name: vigilant-runner-cpp
    <<: *runner-common

  runner-js:
    build:
      context: ./server/runners
      dockerfile: js/Dockerfile
    container_name: vigilant-runner-js
    <<: *runner-common

  runner-java:
    build:
      context: ./server/runners
      dockerfile: java/Dockerfile
    container_name: vigilant-runner-java
    <<: *runner-common

volumes:
  postgres_data: