SERVER_PORT=3333
SERVER_HOST=0.0.0.0
POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_DB=vigilant
POSTGRES_USER=vigilant
POSTGRES_PASSWORD=vigilant123

AUTHN_TOKEN=tokenvalue
ADMIN_AUTH_TOKEN=admintokenvalue

ADMIN_IP_ADDRESS=
ADMIN_SESSION_TIMEOUT=24
DATA_RETENTION_HOURS=72
RATE_LIMIT_PER_MINUTE=120
CLIENT_UPDATE_INTERVAL=5
HIGH_MEMORY_THRESHOLD=500
ENABLE_WEBSOCKETS=true
ALLOW_ORIGIN=*
