# ============================================================
#                   VIGILANT CONFIGURATION
# ============================================================


# ------------------------------------------------------------
# Server
# ------------------------------------------------------------
SERVER_PORT=3333
SERVER_HOST=0.0.0.0


# ------------------------------------------------------------
# Database (PostgreSQL)
# ------------------------------------------------------------
POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_DB=vigilant
POSTGRES_USER=vigilant
POSTGRES_PASSWORD=vigilant123


# ------------------------------------------------------------
# Authentication
# ------------------------------------------------------------
AUTHN_TOKEN=tokenvalue


# ------------------------------------------------------------
# Admin
# ------------------------------------------------------------
ADMIN_AUTH_TOKEN=admintokenvalue
ADMIN_IP_ADDRESS=
ADMIN_SESSION_TIMEOUT=24


# ------------------------------------------------------------
# Security
# ------------------------------------------------------------
JWT_SECRET=
BCRYPT_COST=10


# ------------------------------------------------------------
# Performance & Limits
# ------------------------------------------------------------
DATA_RETENTION_HOURS=72
RATE_LIMIT_PER_MINUTE=120
CLIENT_UPDATE_INTERVAL=5
HIGH_MEMORY_THRESHOLD=500


# ------------------------------------------------------------
# Network & CORS
# ------------------------------------------------------------
ENABLE_WEBSOCKETS=true
ALLOW_ORIGIN=*


# ------------------------------------------------------------
# Encryption
# ------------------------------------------------------------
ENCRYPTION_KEY= nTSThNlBN6s+hYUG21g9hukvy7qAutGHOaJt6PBdrZU=
  
# run: openssl rand -base64 32


# ------------------------------------------------------------
# Minimum Admin App Version
# ------------------------------------------------------------
MINIMUM_ADMIN_APP=v0.0.0


# ------------------------------------------------------------
# Minimum Code App Version
# ------------------------------------------------------------
MINIMUM_ADMIN_APP=v0.0.0


# ------------------------------------------------------------
# Twilio
# ------------------------------------------------------------
TWILIO_ACCOUNT_SID=
TWILIO_API_KEY_SID=
TWILIO_API_KEY_SECRET=
TWILIO_TWIML_APP_SID=
TWILIO_FROM_NUMBER=
