export const TECH_SKILLS = [
  'React',
  'TypeScript',
  'Node.js',
  'Python',
  'JavaScript',
  'Next.js',
  'Vue.js',
  'Angular',
  'AWS',
  'Docker',
  'GraphQL',
  'PostgreSQL',
  'MongoDB',
  'Git',
  'Tailwind CSS',
  'REST API',
];

export const MOCK_INTERVIEWS = [
  {
    id: '1',
    title: 'React Advanced Patterns Interview',
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    duration: 60,
    participants: 12,
    requiredSkills: ['React', 'TypeScript', 'JavaScript'],
    difficulty: 'Intermediate',
    description: 'Deep dive into React hooks, context, and performance optimization.',
  },
  {
    id: '2',
    title: 'Backend Development with Node.js',
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    duration: 90,
    participants: 8,
    requiredSkills: ['Node.js', 'PostgreSQL', 'REST API'],
    difficulty: 'Advanced',
    description: 'Building scalable backend systems with Node.js and Express.',
  },
  {
    id: '3',
    title: 'Cloud Architecture on AWS',
    date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    duration: 75,
    participants: 15,
    requiredSkills: ['AWS', 'Docker'],
    difficulty: 'Intermediate',
    description: 'Designing and deploying cloud applications on AWS.',
  },
  {
    id: '4',
    title: 'Full-Stack Development with Next.js',
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    duration: 120,
    participants: 20,
    requiredSkills: ['Next.js', 'TypeScript', 'PostgreSQL'],
    difficulty: 'Intermediate',
    description: 'Building complete web applications with Next.js and modern tools.',
  },
  {
    id: '5',
    title: 'Python Data Science Fundamentals',
    date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    duration: 60,
    participants: 10,
    requiredSkills: ['Python'],
    difficulty: 'Beginner',
    description: 'Introduction to data science with Python and popular libraries.',
  },
];
