package db

import (
	"database/sql"
	"fmt"
	"log"

	"vigilant/config"

	_ "github.com/lib/pq"
)

var DB *sql.DB

func InitDB(cfg *config.Config) (*sql.DB, error) {
	dsn := cfg.GetDSN()

	db, err := sql.Open("postgres", dsn)
	if err != nil {
		return nil, fmt.Errorf("failed to open database: %w", err)
	}

	if err := db.Ping(); err != nil {
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}

	_, err = db.Exec("SET TIME ZONE 'UTC'")
	if err != nil {
		return nil, fmt.Errorf("failed to set time zone to UTC: %w", err)
	}

	db.SetMaxOpenConns(25)
	db.SetMaxIdleConns(25)

	log.Println("✅ Database connection established and set to UTC")

	DB = db
	return db, nil
}

func RunMigrations(db *sql.DB) error {
	log.Println("Running database migrations...")

	migrations := []string{
		// ========================================
		// MIGRATION 0: Enable pgcrypto for gen_random_uuid()
		// ========================================
		`CREATE EXTENSION IF NOT EXISTS pgcrypto`,

		// ========================================
		// MIGRATION 1: Candidates table
		// id is UUID, generated by postgres automatically
		// ========================================
		`
		CREATE TABLE IF NOT EXISTS candidates (
		id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
		email VARCHAR(255) UNIQUE NOT NULL,
		password_hash VARCHAR(255) NOT NULL,
		full_name VARCHAR(255),
		created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
		is_active BOOLEAN DEFAULT TRUE,
		resume_url VARCHAR(512),
		github_url VARCHAR(512),
		skills VARCHAR(512),
		phone_number VARCHAR(512),
		experience_years SMALLINT CHECK (experience_years >= 0 AND experience_years <= 50),
		onboarding_complete BOOLEAN DEFAULT FALSE,
		interview_current_stage VARCHAR(255),
		interview_next_stage VARCHAR(255),
		current_stage_qualified BOOLEAN DEFAULT FALSE,
		interview_completed BOOLEAN DEFAULT FALSE,
		last_login TIMESTAMPTZ
	);

	CREATE INDEX IF NOT EXISTS idx_candidates_email ON candidates(email);
	CREATE INDEX IF NOT EXISTS idx_candidates_created ON candidates(created_at DESC);
	`,
		// ========================================
		// MIGRATION 2: Candidate sessions table
		// candidate_id is now UUID to match candidates.id
		// ========================================
		`CREATE TABLE IF NOT EXISTS candidate_sessions (
			id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
			candidate_id UUID NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
			session_token TEXT UNIQUE NOT NULL,
			logged_in_at TIMESTAMP DEFAULT NOW(),
			logged_out_at TIMESTAMP,
			last_activity TIMESTAMP DEFAULT NOW(),
			system_type VARCHAR(50),
			os_version VARCHAR(100),
			ip_address INET,
			user_agent TEXT,
			country VARCHAR(100),
			city VARCHAR(100),
			is_active BOOLEAN DEFAULT TRUE,
			created_at TIMESTAMP DEFAULT NOW()
		)`,
		`CREATE INDEX IF NOT EXISTS idx_sessions_candidate ON candidate_sessions(candidate_id)`,
		`CREATE INDEX IF NOT EXISTS idx_sessions_token ON candidate_sessions(session_token)`,
		`CREATE INDEX IF NOT EXISTS idx_sessions_active ON candidate_sessions(is_active, logged_in_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_sessions_ip ON candidate_sessions(ip_address)`,

		// ========================================
		// MIGRATION 12: Hiring Positions table
		// Stores all job postings with UUID and UTC timestamps
		// ========================================
		`CREATE TABLE IF NOT EXISTS hiring_positions (
			id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
			position_title VARCHAR(255) NOT NULL,
			department VARCHAR(255) NOT NULL,
			location VARCHAR(255) NOT NULL,
			employment_type VARCHAR(50) NOT NULL,
			experience_required VARCHAR(100) NOT NULL,
			salary_range_min INTEGER,
			salary_range_max INTEGER,
			salary_range_text VARCHAR(100),
			number_of_openings INTEGER NOT NULL DEFAULT 1,
			job_description TEXT NOT NULL,
			requirements TEXT NOT NULL,
			status VARCHAR(50) DEFAULT 'active',
			created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
			created_by VARCHAR(255),
			updated_by VARCHAR(255),
			is_active BOOLEAN DEFAULT TRUE
		)`,
		`CREATE INDEX IF NOT EXISTS idx_hiring_positions_status ON hiring_positions(status)`,
		`CREATE INDEX IF NOT EXISTS idx_hiring_positions_department ON hiring_positions(department)`,
		`CREATE INDEX IF NOT EXISTS idx_hiring_positions_location ON hiring_positions(location)`,
		`CREATE INDEX IF NOT EXISTS idx_hiring_positions_created_at ON hiring_positions(created_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_hiring_positions_is_active ON hiring_positions(is_active)`,

		// ========================================
		// MIGRATION 13: Trigger for hiring_positions updated_at
		// ========================================
		`CREATE OR REPLACE FUNCTION update_hiring_positions_updated_at()
		RETURNS TRIGGER AS $$
		BEGIN
			NEW.updated_at = CURRENT_TIMESTAMP;
			RETURN NEW;
		END;
		$$ LANGUAGE plpgsql`,
		`DROP TRIGGER IF EXISTS hiring_positions_updated_at_trigger ON hiring_positions`,
		`CREATE TRIGGER hiring_positions_updated_at_trigger
			BEFORE UPDATE ON hiring_positions
			FOR EACH ROW
			EXECUTE FUNCTION update_hiring_positions_updated_at()`,

		`
CREATE TABLE IF NOT EXISTS job_applications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    candidate_id UUID NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
    position_id UUID NOT NULL REFERENCES hiring_positions(id) ON DELETE CASCADE,
    
    status VARCHAR(50) DEFAULT 'applied', 
    -- applied → screening → interviewing → offered → hired / rejected / withdrawn
    
    applied_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    
    cover_letter TEXT,
    notes TEXT,
    
    UNIQUE(candidate_id, position_id) -- prevent duplicate applications
);

CREATE INDEX IF NOT EXISTS idx_job_applications_candidate ON job_applications(candidate_id);
CREATE INDEX IF NOT EXISTS idx_job_applications_position ON job_applications(position_id);
CREATE INDEX IF NOT EXISTS idx_job_applications_status ON job_applications(status);
`,
		`CREATE INDEX IF NOT EXISTS idx_job_applications_candidate ON job_applications(candidate_id);`,
		`CREATE INDEX IF NOT EXISTS idx_job_applications_position ON job_applications(position_id);`,
		`CREATE INDEX IF NOT EXISTS idx_job_applications_status ON job_applications(status);`,

		// ========================================
		// MIGRATION 3: Interview sessions table
		// candidate_id is UUID to match candidates.id
		// session_id is UUID string, server-generated
		// ========================================
		`CREATE TABLE IF NOT EXISTS interview_sessions (
			id SERIAL PRIMARY KEY,
			session_id VARCHAR(255) UNIQUE NOT NULL,
			candidate_id UUID NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
			candidate_session_id UUID REFERENCES candidate_sessions(id) ON DELETE SET NULL,
			application_id UUID REFERENCES job_applications(id) ON DELETE SET NULL,

			interviewer_email VARCHAR(255),
			position VARCHAR(255),
			interview_type VARCHAR(50),
			interview_platform SMALLINT DEFAULT 0 CHECK (interview_platform IN (0)), -- 0: Google Meet
			interview_url TEXT,
			
			scheduled_at TIMESTAMP WITH TIME ZONE, 
			started_at TIMESTAMP WITH TIME ZONE,
			ended_at TIMESTAMP WITH TIME ZONE,
			
			scheduled_duration INTEGER,
			status VARCHAR(50) DEFAULT 'scheduled',
			metadata JSONB,
			notes TEXT,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE INDEX IF NOT EXISTS idx_interview_sessions_id ON interview_sessions(session_id)`,
		`CREATE INDEX IF NOT EXISTS idx_interview_sessions_candidate ON interview_sessions(candidate_id)`,
		`CREATE INDEX IF NOT EXISTS idx_interview_sessions_candidate_session ON interview_sessions(candidate_session_id)`,
		`CREATE INDEX IF NOT EXISTS idx_interview_sessions_application ON interview_sessions(application_id)`,
		`CREATE INDEX IF NOT EXISTS idx_interview_sessions_started ON interview_sessions(started_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_interview_sessions_status ON interview_sessions(status)`,
		`CREATE INDEX IF NOT EXISTS idx_interview_sessions_platform ON interview_sessions(interview_platform)`,
		// ========================================
		// MIGRATION 4: Process logs table
		// ========================================
		`CREATE TABLE IF NOT EXISTS process_logs (
			id BIGSERIAL PRIMARY KEY,
			interview_session_id INTEGER NOT NULL REFERENCES interview_sessions(id) ON DELETE CASCADE,
			candidate_session_id UUID REFERENCES candidate_sessions(id) ON DELETE SET NULL,
			logged_at TIMESTAMP DEFAULT NOW(),
			pid INTEGER NOT NULL,
			ppid INTEGER,
			name VARCHAR(255) NOT NULL,
			path TEXT,
			cmd TEXT,
			memory DECIMAL(10, 2),
			cpu_usage DECIMAL(5, 2),
			is_user_app BOOLEAN DEFAULT FALSE,
			is_gui_app BOOLEAN DEFAULT FALSE,
			username VARCHAR(255),
			process_type VARCHAR(50),
			category VARCHAR(50),
			confidence DECIMAL(3, 2),
			is_unknown BOOLEAN DEFAULT FALSE,
			is_suspicious BOOLEAN DEFAULT FALSE,
			is_electron BOOLEAN DEFAULT FALSE,
			alert_level VARCHAR(20) DEFAULT 'none',
			created_at TIMESTAMP DEFAULT NOW()
		)`,
		`CREATE INDEX IF NOT EXISTS idx_process_logs_interview ON process_logs(interview_session_id)`,
		`CREATE INDEX IF NOT EXISTS idx_process_logs_timestamp ON process_logs(logged_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_process_logs_pid ON process_logs(pid)`,
		`CREATE INDEX IF NOT EXISTS idx_process_logs_name ON process_logs(name)`,
		`CREATE INDEX IF NOT EXISTS idx_process_logs_suspicious ON process_logs(is_suspicious) WHERE is_suspicious = TRUE`,
		`CREATE INDEX IF NOT EXISTS idx_process_logs_unknown ON process_logs(is_unknown) WHERE is_unknown = TRUE`,
		`CREATE INDEX IF NOT EXISTS idx_process_logs_alert ON process_logs(alert_level) WHERE alert_level != 'none'`,

		// ========================================
		// MIGRATION 5: Alert summary table
		// ========================================
		`CREATE TABLE IF NOT EXISTS alert_summary (
			id SERIAL PRIMARY KEY,
			interview_session_id INTEGER UNIQUE NOT NULL REFERENCES interview_sessions(id) ON DELETE CASCADE,
			total_processes INTEGER DEFAULT 0,
			unknown_processes INTEGER DEFAULT 0,
			suspicious_processes INTEGER DEFAULT 0,
			high_memory_processes INTEGER DEFAULT 0,
			electron_processes INTEGER DEFAULT 0,
			critical_alerts INTEGER DEFAULT 0,
			high_alerts INTEGER DEFAULT 0,
			medium_alerts INTEGER DEFAULT 0,
			low_alerts INTEGER DEFAULT 0,
			risk_score DECIMAL(5, 2) DEFAULT 0.0,
			first_alert_at TIMESTAMP,
			last_alert_at TIMESTAMP,
			updated_at TIMESTAMP DEFAULT NOW()
		)`,
		`CREATE INDEX IF NOT EXISTS idx_alert_summary_interview ON alert_summary(interview_session_id)`,
		`CREATE INDEX IF NOT EXISTS idx_alert_summary_risk ON alert_summary(risk_score DESC)`,

		// ========================================
		// MIGRATION 6: Audit log table
		// candidate_id is UUID to match candidates.id
		// ========================================
		`CREATE TABLE IF NOT EXISTS audit_log (
			id BIGSERIAL PRIMARY KEY,
			candidate_id UUID REFERENCES candidates(id) ON DELETE SET NULL,
			action VARCHAR(100) NOT NULL,
			entity_type VARCHAR(50),
			entity_id INTEGER,
			description TEXT,
			metadata JSONB,
			ip_address INET,
			user_agent TEXT,
			created_at TIMESTAMP DEFAULT NOW()
		)`,
		`CREATE INDEX IF NOT EXISTS idx_audit_log_candidate ON audit_log(candidate_id)`,
		`CREATE INDEX IF NOT EXISTS idx_audit_log_action ON audit_log(action)`,
		`CREATE INDEX IF NOT EXISTS idx_audit_log_created ON audit_log(created_at DESC)`,

		// ========================================
		// MIGRATION 7: Trigger function for alert summary
		// ========================================
		`CREATE OR REPLACE FUNCTION update_alert_summary()
		RETURNS TRIGGER AS $$
		BEGIN
			INSERT INTO alert_summary (
				interview_session_id,
				total_processes,
				unknown_processes,
				suspicious_processes,
				high_memory_processes,
				electron_processes
			)
			VALUES (
				NEW.interview_session_id,
				1,
				CASE WHEN NEW.is_unknown THEN 1 ELSE 0 END,
				CASE WHEN NEW.is_suspicious THEN 1 ELSE 0 END,
				CASE WHEN NEW.memory > 500 THEN 1 ELSE 0 END,
				CASE WHEN NEW.is_electron THEN 1 ELSE 0 END
			)
			ON CONFLICT (interview_session_id) DO UPDATE SET
				total_processes = alert_summary.total_processes + 1,
				unknown_processes = alert_summary.unknown_processes + CASE WHEN NEW.is_unknown THEN 1 ELSE 0 END,
				suspicious_processes = alert_summary.suspicious_processes + CASE WHEN NEW.is_suspicious THEN 1 ELSE 0 END,
				high_memory_processes = alert_summary.high_memory_processes + CASE WHEN NEW.memory > 500 THEN 1 ELSE 0 END,
				electron_processes = alert_summary.electron_processes + CASE WHEN NEW.is_electron THEN 1 ELSE 0 END,
				critical_alerts = alert_summary.critical_alerts + CASE WHEN NEW.alert_level = 'critical' THEN 1 ELSE 0 END,
				high_alerts = alert_summary.high_alerts + CASE WHEN NEW.alert_level = 'high' THEN 1 ELSE 0 END,
				medium_alerts = alert_summary.medium_alerts + CASE WHEN NEW.alert_level = 'medium' THEN 1 ELSE 0 END,
				low_alerts = alert_summary.low_alerts + CASE WHEN NEW.alert_level = 'low' THEN 1 ELSE 0 END,
				last_alert_at = CASE WHEN NEW.is_suspicious OR NEW.is_unknown THEN NOW() ELSE alert_summary.last_alert_at END,
				updated_at = NOW();

			RETURN NEW;
		END;
		$$ LANGUAGE plpgsql`,

		// ========================================
		// MIGRATION 8: Create trigger
		// ========================================
		`DROP TRIGGER IF EXISTS trigger_update_alert_summary ON process_logs`,
		`CREATE TRIGGER trigger_update_alert_summary
			AFTER INSERT ON process_logs
			FOR EACH ROW
			EXECUTE FUNCTION update_alert_summary()`,

		// ========================================
		// MIGRATION 9: Process reports table
		// ========================================
		`CREATE TABLE IF NOT EXISTS process_reports (
			id BIGSERIAL PRIMARY KEY,
			session_id VARCHAR(255) NOT NULL REFERENCES interview_sessions(session_id) ON DELETE CASCADE,
			processes JSONB,
			alert_count INTEGER DEFAULT 0,
			high_memory_alerts INTEGER DEFAULT 0,
			unknown_electron_alerts INTEGER DEFAULT 0,
			reported_at TIMESTAMP DEFAULT NOW(),
			created_at TIMESTAMP DEFAULT NOW()
		)`,
		`CREATE INDEX IF NOT EXISTS idx_process_reports_session ON process_reports(session_id)`,
		`CREATE INDEX IF NOT EXISTS idx_process_reports_reported ON process_reports(reported_at DESC)`,

		// ========================================
		// MIGRATION 10: Code Judge table
		// ========================================

		`CREATE TABLE IF NOT EXISTS judge_submissions (
            id         UUID      PRIMARY KEY DEFAULT gen_random_uuid(),
            language   TEXT      NOT NULL,
            code       TEXT      NOT NULL,
            stdout     TEXT      NOT NULL DEFAULT '',
            stderr     TEXT      NOT NULL DEFAULT '',
            exit_code  INT       NOT NULL DEFAULT 0,
            time_ms    BIGINT    NOT NULL DEFAULT 0,
            memory_kb  BIGINT    NOT NULL DEFAULT 0,
            status     TEXT      NOT NULL DEFAULT 'pending',
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )`,
		`CREATE INDEX IF NOT EXISTS idx_judge_submissions_lang    ON judge_submissions(language)`,
		`CREATE INDEX IF NOT EXISTS idx_judge_submissions_status  ON judge_submissions(status)`,
		`CREATE INDEX IF NOT EXISTS idx_judge_submissions_created ON judge_submissions(created_at DESC)`,

		// ========================================
		// MIGRATION 11: AWS SES credentials table
		// Credentials are encrypted with AES-GCM before storage.
		// Only one row ever exists (single global config).
		// ========================================
		`CREATE TABLE IF NOT EXISTS email_config (
			id                    SERIAL PRIMARY KEY,
			aws_region            TEXT NOT NULL,
			aws_access_key_id     TEXT NOT NULL,
			aws_secret_access_key TEXT NOT NULL,
			ses_from_email        TEXT NOT NULL,
			ses_login_url         TEXT NOT NULL,
			created_at            TIMESTAMP DEFAULT NOW(),
			updated_at            TIMESTAMP DEFAULT NOW()
		)`,

		// ========================================
		// MIGRATION 14: Hiring Candidates table
		// For tracking applicants with interview tracking
		// ========================================
		`CREATE TABLE IF NOT EXISTS hiring_candidates (
			id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
			email VARCHAR(255) UNIQUE NOT NULL,
			password_hash VARCHAR(255) NOT NULL,
			full_name VARCHAR(255),
			position_id UUID NOT NULL REFERENCES hiring_positions(id) ON DELETE CASCADE,
			created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
			is_active BOOLEAN DEFAULT TRUE,
			resume_url VARCHAR(512),
			github_url VARCHAR(512),
			skills VARCHAR(512),
			phone_number VARCHAR(512),
			experience_years SMALLINT CHECK (experience_years >= 0 AND experience_years <= 50),
			onboarding_complete BOOLEAN DEFAULT FALSE,
			interview_current_stage VARCHAR(255),
			interview_next_stage VARCHAR(255),
			current_stage_qualified BOOLEAN DEFAULT FALSE,
			interview_completed BOOLEAN DEFAULT FALSE,
			last_login TIMESTAMPTZ
		)`,
		`CREATE INDEX IF NOT EXISTS idx_hiring_candidates_email ON hiring_candidates(email)`,
		`CREATE INDEX IF NOT EXISTS idx_hiring_candidates_position_id ON hiring_candidates(position_id)`,
		`CREATE INDEX IF NOT EXISTS idx_hiring_candidates_is_active ON hiring_candidates(is_active)`,
		`CREATE INDEX IF NOT EXISTS idx_hiring_candidates_interview_current_stage ON hiring_candidates(interview_current_stage)`,
		`CREATE INDEX IF NOT EXISTS idx_hiring_candidates_interview_completed ON hiring_candidates(interview_completed)`,
		`CREATE INDEX IF NOT EXISTS idx_hiring_candidates_created_at ON hiring_candidates(created_at DESC)`,

		// ========================================
		// MIGRATION 15: Trigger for hiring_candidates updated_at
		// ========================================
		`CREATE OR REPLACE FUNCTION update_hiring_candidates_updated_at()
		RETURNS TRIGGER AS $$
		BEGIN
			NEW.updated_at = CURRENT_TIMESTAMP;
			RETURN NEW;
		END;
		$$ LANGUAGE plpgsql`,
		`DROP TRIGGER IF EXISTS hiring_candidates_updated_at_trigger ON hiring_candidates`,
		`CREATE TRIGGER hiring_candidates_updated_at_trigger
			BEFORE UPDATE ON hiring_candidates
			FOR EACH ROW
			EXECUTE FUNCTION update_hiring_candidates_updated_at()`,

		// ========================================
		// MIGRATION 16: Google Credentails
		// ========================================

		`CREATE TABLE IF NOT EXISTS google_credentials (
    id SERIAL PRIMARY KEY,
    credential_name VARCHAR(255) NOT NULL UNIQUE,
    organization_id UUID,
    user_id UUID,
    service_account_email VARCHAR(255) NOT NULL,
    project_id VARCHAR(255) NOT NULL,
    private_key_id VARCHAR(255) NOT NULL,
    private_key TEXT NOT NULL,
    client_email VARCHAR(255) NOT NULL,
    client_id VARCHAR(255) NOT NULL,
    access_token TEXT,
    refresh_token TEXT,
    token_expiry TIMESTAMP WITH TIME ZONE,
    scopes TEXT[],
    credentials_json JSONB,
    credential_type VARCHAR(50) DEFAULT 'service_account',
    is_active BOOLEAN DEFAULT true,
    is_default BOOLEAN DEFAULT false,
    delegated_admin_email VARCHAR(255),
    subject_email VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    last_used_at TIMESTAMP WITH TIME ZONE
)`,

		// Partial unique index — only one default allowed per org (replaces the broken CONSTRAINT ... WHERE)
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_google_credentials_one_default_per_org
    ON google_credentials (organization_id, is_default)
    WHERE is_default = true`,

		`CREATE INDEX IF NOT EXISTS idx_google_credentials_active ON google_credentials(is_active)`,
		`CREATE INDEX IF NOT EXISTS idx_google_credentials_default ON google_credentials(is_default) WHERE is_default = true`,
		`CREATE INDEX IF NOT EXISTS idx_google_credentials_org ON google_credentials(organization_id)`,
		`CREATE INDEX IF NOT EXISTS idx_google_credentials_type ON google_credentials(credential_type)`,

		`CREATE OR REPLACE FUNCTION update_google_credentials_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql`,

		`DROP TRIGGER IF EXISTS trigger_update_google_credentials_timestamp ON google_credentials`,

		`CREATE TRIGGER trigger_update_google_credentials_timestamp
BEFORE UPDATE ON google_credentials
FOR EACH ROW
EXECUTE FUNCTION update_google_credentials_updated_at()`,

		// MIGRATION 17: Email jobs queue
		`CREATE TABLE IF NOT EXISTS email_jobs (
    id          BIGSERIAL PRIMARY KEY,
    
    -- Routing
    to_email    TEXT NOT NULL,
    to_name     TEXT,
    from_email  TEXT NOT NULL,
    reply_to    TEXT,
    
    -- Content
    subject     TEXT NOT NULL,
    body_html   TEXT NOT NULL,
    body_text   TEXT,
    template    VARCHAR(100),        -- e.g. "interview_invite", "welcome"
    template_data JSONB,             -- data passed to template
    
    -- Context (for traceability)
    entity_type VARCHAR(50),         -- e.g. "interview_session", "candidate"
    entity_id   TEXT,                -- the ID of the related entity
    triggered_by TEXT,               -- e.g. "create_interview", "bulk_invite"
    
    -- Queue management
    status      VARCHAR(20) DEFAULT 'pending', -- pending, sending, sent, failed, cancelled
    priority    SMALLINT DEFAULT 0,            -- 0=normal, 1=high
    attempts    SMALLINT DEFAULT 0,
    max_attempts SMALLINT DEFAULT 3,
    scheduled_at TIMESTAMPTZ DEFAULT NOW(),    -- send no earlier than this
    
    -- Result
    sent_at     TIMESTAMPTZ,
    failed_at   TIMESTAMPTZ,
    error       TEXT,
    provider_message_id TEXT,        -- SES message ID for traceability
    
    -- Audit
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
)`,

		`CREATE INDEX IF NOT EXISTS idx_email_jobs_status ON email_jobs(status, scheduled_at) WHERE status = 'pending'`,
		`CREATE INDEX IF NOT EXISTS idx_email_jobs_entity ON email_jobs(entity_type, entity_id)`,
		`CREATE INDEX IF NOT EXISTS idx_email_jobs_created ON email_jobs(created_at DESC)`,

		// MIGRATION 18: Email send log (immutable record of every attempt)
		`CREATE TABLE IF NOT EXISTS email_logs (
    id          BIGSERIAL PRIMARY KEY,
    job_id      BIGINT REFERENCES email_jobs(id) ON DELETE SET NULL,
    
    -- What was sent (snapshot at send time)
    to_email    TEXT NOT NULL,
    from_email  TEXT NOT NULL,
    subject     TEXT NOT NULL,
    body_html   TEXT NOT NULL,       -- full content logged for traceability
    
    -- Result
    status      VARCHAR(20) NOT NULL, -- sent, failed
    provider_message_id TEXT,
    error       TEXT,
    attempt     SMALLINT NOT NULL,
    
    -- Timing
    sent_at     TIMESTAMPTZ DEFAULT NOW()
)`,
		`CREATE INDEX IF NOT EXISTS idx_email_logs_job ON email_logs(job_id)`,
		`CREATE INDEX IF NOT EXISTS idx_email_logs_to ON email_logs(to_email)`,
		`CREATE INDEX IF NOT EXISTS idx_email_logs_sent ON email_logs(sent_at DESC)`,
	}

	for i, migration := range migrations {
		if _, err := db.Exec(migration); err != nil {
			return fmt.Errorf("migration %d failed: %w", i+1, err)
		}
	}

	log.Println("✅ Database migrations completed")
	return nil
}
